### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by kusma** [fiveisprime/atom-make-runner#20]
[Enter steps to reproduce below:]

1. install make-runner
2. run "Make Runner: run" from the command-palette

**Atom Version**: 0.181.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [make-runner](git://github.com/fiveisprime/atom-make-runner) package, v1.1.2

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:201

TypeError: Arguments to path.join must be strings
  at f (path.js:201:13)
  at Object.filter (native)
  at Object.win32.join (path.js:206:38)
  at Object.module.exports.run (C:\Users\erik\.atom\packages\make-runner\lib\make-runner.coffee:81:24)
  at atom-text-editor.<anonymous> (C:\Users\erik\.atom\packages\make-runner\lib\make-runner.coffee:39:66)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\erik\AppData\Local\atom\app-0.181.0\resources\app\src\window-event-handler.js:176:20)

```

### Commands

```
     -0:35.1 symbols-view:toggle-file-symbols (atom-text-editor.editor)
     -0:32.6 editor:consolidate-selections (atom-text-editor.editor)
     -0:09.2 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:05.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.3 core:confirm (atom-text-editor.editor.mini)
     -0:03.3 make-runner:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
language-csharp, v0.5.0
language-uno, v0.1.0
make-runner, v1.1.2

# Dev
No dev packages
```

**Comment by kusma** [comment]
This is when running from an unsaved file, so I guess what happens is editor.getUri() returning null.
